language: php

php:
  - 5.4
  - 5.5

before_script:
  - mkdir data/DoctrineORMModule/Proxy -p
  - phpenv rehash
  - composer install --dev --prefer-source

script: vendor/bin/phpunit --configuration tests/travis.xml  --coverage-text --coverage-clover ./build/logs/clover.xml

after_script:
  - vendor/bin/coveralls -v
