    <div class="btn-toolbar">
        <a href="<?php echo $this->url('crud', array('controller' => 'orgao', 'action' => 'novo')) ?>" class="btn btn-primary">Adicionar</a>
    </div>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th>Nome</th>
                <th width="80">Ações</th>
            </tr>
        </thead>
        <?php foreach ($data as $orgao):
        ?>
        <tr>
            <td><?= $orgao->nome ?></td>
            <td>
                <a href="<?php echo $this->url('crud', array('controller' => 'orgao', 'action' => 'editar', 'id' => $orgao->id)) ?>" class="btn btn-small" rel="tooltip" title="Editar"><i class="icon-edit"></i></a>
                <a href="<?php echo $this->url('crud', array('controller' => 'orgao', 'action' => 'excluir', 'id' => $orgao->id)) ?>" class="btn btn-small btn-danger" rel="tooltip" title="Excluir"><i class="icon-remove"></i></a>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
