<?php
$form->prepare();
?>

<?= $this->form()->openTag($form); ?>

<?php if (!$form->get('id')->getValue()): ?>
<legend>Adicionar Órgão</legend>
<?php else: ?>
<legend>Editar Órgão</legend>
<?php endif; ?>

<?= $this->flashMessage(); ?>

<?= $this->formHidden($form->get('id')); ?>
<?= $this->bootstrapRow($form->get('nome')); ?>
<?= $this->bootstrapRow($form->get('responsavel')); ?>
<?= $this->bootstrapRow($form->get('email')); ?>
<?= $this->bootstrapRow($form->get('telefone')); ?>

<div class="control-group">
    <div class="controls">
    <button class="btn">Salvar</button> ou <a href="<?php echo $this->url('crud', array('controller' => 'orgao')) ?>">Voltar</a>
    </div>
</div>

<?= $this->form()->closeTag(); ?>
