<?php
$form->prepare();
?>

<?= $this->form()->openTag($form); ?>

<?= $this->flashMessage(); ?>

<?= $this->formHidden($form->get('id')); ?>
<?= $this->bootstrapRow($form->get('nome')); ?>
<?= $this->bootstrapRow($form->get('sigla')); ?>

<div class="control-group">
    <div class="controls">
    <button class="btn">Salvar</button> ou <a href="<?php echo $this->url('crud', array('controller' => 'site')) ?>">Voltar</a>
    </div>
</div>

<?= $this->form()->closeTag(); ?>
