<h2>Login</h2>

<hr />

<?php
$form->prepare();
?>

<?= $this->flashMessage(); ?>

<?= $this->form()->openTag($form); ?>

<?= $this->bootstrapRow($form->get('email'))->prependIcon('icon-envelope'); ?>
<?= $this->bootstrapRow($form->get('senha'))->prependIcon('icon-key'); ?>

<?= $this->formHidden($form->get('security')); ?>

<div class="control-group">
    <div class="controls">
    <button class="btn">Login</button> ou <a href="">Voltar</a>
    </div>
</div>

<?= $this->form()->closeTag(); ?>